# Non-Communicable Disease Burden (NCD)

This data shows the NCD burden in Egypt, Nigeria and Uganda over time.

```{r include=FALSE}
#set chunk options
knitr::opts_chunk$set(message = FALSE, echo = FALSE, warning = FALSE)
```

```{r include=FALSE}
# Load necessary packages
pacman::p_load(tidyverse, knitr, here)

# Import the non-communicable diseases data
data_ncd <- read_csv(here("data", "burden-of-disease-ncd.csv"))
data_ncd
```

## Table of Estimates for NCD Burden Over Time

```{r message = FALSE}
# Here render a table for the DALY burden over time for the three countries 

# You should pivot the data to show each country in a separate column.
# Use kable() from the knitr package to render the table.

ncd_table <- data_ncd %>%
  filter(Entity %in% c("Egypt", "Uganda", "Nigeria")) %>%
  rename(DALYS =`DALYs (Disability-Adjusted Life Years) - Non-communicable diseases - Sex: Both - Age: Age-standardized (Rate)`) 

ncd_table %>% 
  select(Entity, Year, DALYS) %>% 
  pivot_wider(names_from = Entity, values_from = DALYS 
            )


kable(ncd_table)# a table showing the DALYs over time in the 3 countries
  
```

```{}
```

## Plot Showing Trends in NCD Burden Over Time

```{r}
# Here, plot a line graph showing the trend of DALY burden for the chosen countries over time. You can use ggplot2 to create this plot. Each country's line should be a different color.

ggplot(ncd_table,mapping = aes(x = Year,
                               y = DALYS,
                               color = Entity)) +
  geom_line()


```

## Summary of NCD Burden Findings

Egypt appears to have a higher NCD burden over time compared to Nigeria or Uganda.
